Remove Uncessary Libraries and interfaces from elixir merge.
Gamealition/GPrism pull request #7
Opened 2017-05-30 03:09 UTC by Narimm

Much of this commit represents the removal of unnecessary code - one might argue some of it improved readability, however, I think the declarations are enough.  There is still far too many jdoc warnings but then as bukkit devs that was never a forte.  Other than that I think its pretty straight forward - you may want to review the item utility that gets a nice name for item metadata ... we had historically added some stuff to this.  

Otherwise commit message:

Remove unnecessary declarations
Streamline some Code.

Add new purge frequency config option will purge at this frequency per day at regular intervals:
ie 2 would be every 12 hrs (which is the default), 3 would be every 8hrs...
```
prism:
      purge:
         perday: 2
```

2017-05-31 17:57 UTC, RoyCurtis requested changes

2017-05-31 17:57 UTC, RoyCurtis commented on src/main/java/com/helion3/prism/libs/elixr/ItemUtils.java
> +				return false;
Don't suppose this could be spaces instead of tabs, please?

2017-05-31 17:57 UTC, RoyCurtis commented on src/main/java/me/botsko/prism/Prism.java
> +    private static volatile DataSource pool = new DataSource();
Forgive my ignorance but, what does this change do? What effect does it have on PRISM? Has it been tested?

2017-05-31 17:57 UTC, RoyCurtis commented on src/main/java/me/botsko/prism/Prism.java
> +        Integer purgeCycleTime = Math.round(24/getConfig().getInt("prism.purge.perday",2));
If I recall correctly, `Math.round` is not needed here as integer division still results in an integer, right?

2017-05-31 17:57 UTC, RoyCurtis commented on src/main/java/me/botsko/prism/actions/BlockChangeAction.java
> +        if( actionData instanceof SkullActionData ) {
Thanks for adding these; however:

1. Could this be moved to a separate commit, please?
2. Is this duplicating a lot of code from `getNiceName` in `BlockAction`? If so, could these be moved to a common utility method instead?

2017-05-31 17:57 UTC, RoyCurtis commented on src/main/java/me/botsko/prism/players/PlayerIdentification.java
> -            if(rs != null) try { rs.close(); } catch (SQLException e) {}
Why was this removed? If the result set is closeable, should it not be closed?

2017-05-31 17:57 UTC, RoyCurtis commented on src/main/java/me/botsko/prism/utils/BlockUtils.java
> +    public static boolean isDoor(Material m) {
This method is not being used anywhere in this change set, as far as I can find...

2017-05-31 17:58 UTC, RoyCurtis commented
Thank you very much for this!

However, it's quite a big PR. I've gone through and made comments, requesting changes and asking for clarification on certain changes.

Also, can you please move the purge frequency config addition to a separate pull request or commit?

2017-05-31 19:04 UTC, md678685 commented on src/main/java/me/botsko/prism/Prism.java
> +    private static volatile DataSource pool = new DataSource();
`volatile` means that the variable is consistent across threads as it isn't cached by the CPU.

2017-06-01 08:25 UTC, Narimm commented
No drama I will get to this tomorrow

2017-06-05 00:21 UTC, Narimm commented on src/main/java/me/botsko/prism/Prism.java
> +        Integer purgeCycleTime = Math.round(24/getConfig().getInt("prism.purge.perday",2));
I thought it best to implicitly declare it ...to ensure we dont get casting errors later on... but we can go back and rely on type casting

2017-06-05 00:26 UTC, Narimm commented on src/main/java/me/botsko/prism/players/PlayerIdentification.java
> -            if(rs != null) try { rs.close(); } catch (SQLException e) {}
it was removed because it is never used....take a look we never actually get a result set...just execute the prepared statement....

2017-06-05 00:33 UTC, Narimm commented on src/main/java/me/botsko/prism/utils/BlockUtils.java
> +    public static boolean isDoor(Material m) {
I reverted it - I assume we had it as we hadnt used the elixir import at that stage...I have removed this

2017-06-05 01:22 UTC, Narimm commented on src/main/java/com/helion3/prism/libs/elixr/ItemUtils.java
> +				return false;
done

2017-06-05 01:57 UTC, Narimm commented
I have removed the changes request and moved them to seperate PR's

2017-06-05 06:34 UTC, RoyCurtis commented on src/main/java/me/botsko/prism/players/PlayerIdentification.java
> -            if(rs != null) try { rs.close(); } catch (SQLException e) {}
Understood; thanks!

2017-06-05 06:34 UTC, RoyCurtis commented
Thank you very much for this! Will pull in the other changes too, and then test all of this out

2017-06-05 06:37 UTC, merged